//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazılımSınama
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SinavOtomasyonuEntities : DbContext
    {
        public SinavOtomasyonuEntities()
            : base("name=SinavOtomasyonuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_İstatistik> Tbl_İstatistik { get; set; }
        public virtual DbSet<Tbl_Kategoriler> Tbl_Kategoriler { get; set; }
        public virtual DbSet<Tbl_Kisi> Tbl_Kisi { get; set; }
        public virtual DbSet<Tbl_KisiRol> Tbl_KisiRol { get; set; }
        public virtual DbSet<Tbl_Sinav> Tbl_Sinav { get; set; }
        public virtual DbSet<Tbl_Sorular> Tbl_Sorular { get; set; }
    }
}
