//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazılımSınama
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kisi
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string kullaniciAdi { get; set; }
        public string sifre { get; set; }
        public Nullable<int> rolID { get; set; }
    }
}
