//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazılımSınama
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sorular
    {
        public int ID { get; set; }
        public string Soru { get; set; }
        public string Secenek1 { get; set; }
        public string Secenek2 { get; set; }
        public string Secenek3 { get; set; }
        public string DogruSecenek { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public string SoruResmi { get; set; }
    }
}
